import { defineConfig } from 'astro/config';
import fs from 'node:fs';

// Merged keyword pages -> canonical page (generated by scripts/enrich-seo-pages.mjs)
const readJson = (p) => (fs.existsSync(new URL(p, import.meta.url)) ? JSON.parse(fs.readFileSync(new URL(p, import.meta.url), 'utf8')) : {});
const manual = Object.fromEntries(Object.entries(readJson('./src/data/seo/redirects.manual.json')).filter(([k]) => !k.startsWith('_')));
const redirects = { ...readJson('./src/data/redirects.json'), ...manual };

// https://astro.build/config
export default defineConfig({
  site: 'https://4ksubscriptioniptv.com',
  output: 'static',
  redirects,
  compressHTML: true,
  build: {
    format: 'directory',
    inlineStylesheets: 'auto'
  },
  vite: {
    build: {
      cssMinify: true,
      minify: 'esbuild'
    }
  }
});
