// Runs before every build (npm "prebuild"). Produces the performance assets in public/:
//   public/fonts/*.woff2        self-hosted Inter + Outfit (latin, variable) instead of Google Fonts
//   public/fonts/fa/*           Font Awesome subset: only the icons the site really uses (+ fa.css)
//   public/images/**/*.webp     WebP copy of every JPG / PNG (postbuild switches the HTML to them)
//
// No manual step needed: add an icon class like fa-solid fa-star anywhere in src/ and it is picked up on the next build.
import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';
import sharp from 'sharp';
import { fontawesomeSubset } from 'fontawesome-subset';

const require = createRequire(import.meta.url);
const root = process.cwd();
const PUB = path.join(root, 'public');
const rd = (f) => fs.readFileSync(f, 'utf8');
fs.mkdirSync(path.join(PUB, 'fonts/fa'), { recursive: true });

// ------------------------------------------------------------------ 1) fonts
const copy = (pkg, file, out) => {
  const src = path.join(root, 'node_modules', pkg, 'files', file);
  if (!fs.existsSync(src)) throw new Error('font file missing: ' + src);
  fs.copyFileSync(src, path.join(PUB, 'fonts', out));
};
copy('@fontsource-variable/inter', 'inter-latin-wght-normal.woff2', 'inter-latin-wght-normal.woff2');
copy('@fontsource-variable/outfit', 'outfit-latin-wght-normal.woff2', 'outfit-latin-wght-normal.woff2');

// ------------------------------------------------------------------ 2) Font Awesome subset
const meta = JSON.parse(rd(path.join(root, 'node_modules/@fortawesome/fontawesome-free/metadata/icon-families.json')));
const byName = new Map(); // class name (incl. aliases) -> { unicode, styles }
for (const [name, ic] of Object.entries(meta)) {
  const info = { unicode: ic.unicode, styles: Object.keys((ic.svgs && ic.svgs.classic) || {}) };
  byName.set(name, info);
  for (const a of ic.aliases?.names || []) byName.set(a, info);
}

const walk = (d, a = []) => { for (const f of fs.readdirSync(d)) { const p = path.join(d, f); if (fs.statSync(p).isDirectory()) walk(p, a); else if (/\.(astro|mjs|js|ts|json|md)$/.test(f)) a.push(p); } return a; };
const files = walk(path.join(root, 'src'));
const used = new Map(); // name -> Set(styles requested explicitly)
const utility = new Set();
for (const f of files) {
  const t = rd(f);
  for (const m of t.matchAll(/\bfa-(solid|regular|brands)\s+fa-([a-z0-9-]+)/g)) { (used.get(m[2]) || used.set(m[2], new Set()).get(m[2])).add(m[1]); }
  for (const m of t.matchAll(/\bfa-([a-z0-9-]+)\b/g)) {
    const n = m[1];
    if (/^(solid|regular|brands)$/.test(n)) continue;
    if (/^(spin|pulse|fw|lg|xs|sm|1x|2x|3x|4x|5x|beat|bounce|fade|flip|shake|spin-pulse|spin-reverse|rotate-90|rotate-180|rotate-270)$/.test(n)) { utility.add(n); continue; }
    if (byName.has(n) && !used.has(n)) used.set(n, new Set());
  }
}
const sets = { solid: new Set(), regular: new Set(), brands: new Set() };
const rules = [];
const missing = [];
for (const [name, explicit] of used) {
  const info = byName.get(name);
  if (!info) { missing.push(name); continue; }
  const styles = explicit.size ? [...explicit] : info.styles.includes('solid') ? ['solid'] : [info.styles[0]];
  for (const s of styles) if (info.styles.includes(s)) sets[s].add(info.unicode); else if (info.styles.includes('solid')) sets.solid.add(info.unicode);
  rules.push(`.fa-${name}::before{content:"\\${info.unicode}"}`);
}
await fontawesomeSubset(
  { solid: [...sets.solid], regular: [...sets.regular], brands: [...sets.brands] },
  path.join(PUB, 'fonts/fa'),
  { package: 'free', targetFormats: ['woff2'] }
);
// remove the unused ttf if the tool left one
for (const f of fs.readdirSync(path.join(PUB, 'fonts/fa'))) if (f.endsWith('.ttf')) fs.unlinkSync(path.join(PUB, 'fonts/fa', f));

const utilityCss = {
  spin: '.fa-spin{animation:fa-spin 2s linear infinite}@keyframes fa-spin{to{transform:rotate(360deg)}}',
  fw: '.fa-fw{text-align:center;width:1.25em}',
  lg: '.fa-lg{font-size:1.25em;line-height:.05em;vertical-align:-.0667em}',
  xs: '.fa-xs{font-size:.75em}', sm: '.fa-sm{font-size:.875em}',
  '2x': '.fa-2x{font-size:2em}', '3x': '.fa-3x{font-size:3em}', '1x': '.fa-1x{font-size:1em}',
};
const css =
  `/* generated by scripts/build-assets.mjs: Font Awesome Free ${meta['house'] ? '' : ''}subset (${used.size} icons) */\n` +
  `@font-face{font-family:"Font Awesome 6 Free";font-style:normal;font-weight:900;font-display:swap;src:url(/fonts/fa/fa-solid-900.woff2) format("woff2")}\n` +
  `@font-face{font-family:"Font Awesome 6 Free";font-style:normal;font-weight:400;font-display:swap;src:url(/fonts/fa/fa-regular-400.woff2) format("woff2")}\n` +
  `@font-face{font-family:"Font Awesome 6 Brands";font-style:normal;font-weight:400;font-display:swap;src:url(/fonts/fa/fa-brands-400.woff2) format("woff2")}\n` +
  `.fa-solid,.fa-regular,.fa-brands,.fas,.far,.fab,.fa{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;display:inline-block;font-style:normal;font-variant:normal;line-height:1;text-rendering:auto}\n` +
  `.fa-solid,.fas,.fa{font-family:"Font Awesome 6 Free";font-weight:900}.fa-regular,.far{font-family:"Font Awesome 6 Free";font-weight:400}.fa-brands,.fab{font-family:"Font Awesome 6 Brands";font-weight:400}\n` +
  [...utility].map((u) => utilityCss[u]).filter(Boolean).join('\n') + '\n' +
  rules.sort().join('\n') + '\n';
fs.writeFileSync(path.join(PUB, 'fonts/fa/fa.css'), css);
const faBytes = fs.readdirSync(path.join(PUB, 'fonts/fa')).reduce((n, f) => n + fs.statSync(path.join(PUB, 'fonts/fa', f)).size, 0);
console.log(`assets: Font Awesome subset ${used.size} icons (${(faBytes / 1024).toFixed(0)} KB total)${missing.length ? '; unknown icon classes ignored: ' + missing.join(', ') : ''}`);

// ------------------------------------------------------------------ 3) WebP copies of images
let made = 0, skipped = 0, saved = 0;
const walkImg = (d, a = []) => { for (const f of fs.readdirSync(d)) { const p = path.join(d, f); if (fs.statSync(p).isDirectory()) walkImg(p, a); else if (/\.(jpe?g|png)$/i.test(f)) a.push(p); } return a; };
for (const f of walkImg(path.join(PUB, 'images'))) {
  const out = f.replace(/\.(jpe?g|png)$/i, '.webp');
  const st = fs.statSync(f);
  if (st.size < 2048) { skipped++; continue; }
  if (fs.existsSync(out) && fs.statSync(out).mtimeMs >= st.mtimeMs) { skipped++; continue; }
  const buf = await sharp(fs.readFileSync(f), { failOn: 'none' }).resize({ width: 1200, withoutEnlargement: true }).webp({ quality: 72, alphaQuality: 85, effort: 5 }).toBuffer();
  if (buf.length >= st.size) { skipped++; continue; } // keep the original when WebP is not smaller
  fs.writeFileSync(out, buf); made++; saved += st.size - buf.length;
}
console.log(`assets: WebP ${made} new (${(saved / 1048576).toFixed(1)} MB smaller), ${skipped} unchanged`);
