// Runs automatically after `astro build` (npm "postbuild").
// Rewrites every internal link in dist/*.html so it follows the URL policy from site-config.json
// ("trailingSlash": true | false). That keeps links, canonicals, sitemap and hreflang identical.
import fs from 'fs';
import path from 'path';
import sharp from 'sharp';

const cfg = JSON.parse(fs.readFileSync('src/data/site-config.json', 'utf8'));
const domain = cfg.domain;
const slash = !!cfg.trailingSlash;
const DIST = 'dist';

function policy(p) {
  if (!p || p === '/') return '/';
  const m = p.match(/^([^?#]*)(.*)$/);
  let base = m[1];
  const last = base.split('/').filter(Boolean).pop() || '';
  if (/\.[a-z0-9]{2,5}$/i.test(last)) return p;
  base = base.replace(/\/+$/, '');
  if (slash) base += '/';
  return (base || '/') + m[2];
}
const skip = (u) => /^\/(_astro|images|flags|data)\//.test(u) || u.startsWith('//');

// ---------------- images: WebP, intrinsic size, decoding, LCP priority ----------------
const imageStats = { webp: 0, dims: 0, decoding: 0, priority: 0 };
const dimCache = new Map();
async function dimsOf(src) {
  if (dimCache.has(src)) return dimCache.get(src);
  let d = null;
  const file = path.join(DIST, decodeURI(src));
  if (fs.existsSync(file) && /\.(webp|jpe?g|png|gif|avif)$/i.test(file)) { try { const m = await sharp(file).metadata(); if (m.width && m.height) d = [m.width, m.height]; } catch {} }
  dimCache.set(src, d);
  return d;
}
const toWebp = (u) => {
  const m = u.match(/^(\/images\/.+)\.(jpe?g|png)$/i);
  if (!m) return u;
  const w = m[1] + '.webp';
  return fs.existsSync(path.join(DIST, decodeURI(w))) ? w : u;
};
async function optimiseImages(h) {
  // 1) switch to WebP when a smaller copy exists. Only in src / srcset / url(), never in <meta> or JSON-LD (social images stay PNG)
  h = h.replace(/(\ssrc=)"(\/images\/[^"]+\.(?:jpe?g|png))"/gi, (all, a, u) => { const n = toWebp(u); if (n !== u) imageStats.webp++; return `${a}"${n}"`; });
  h = h.replace(/(\ssrcset=)"([^"]+)"/gi, (all, a, v) => `${a}"${v.split(',').map((p) => { const [u, ...r] = p.trim().split(/\s+/); return [toWebp(u), ...r].join(' '); }).join(', ')}"`);
  h = h.replace(/url\((['"]?)(\/images\/[^)'"]+\.(?:jpe?g|png))\1\)/gi, (all, q, u) => `url(${q}${toWebp(u)}${q})`);
  // 2) <img> tags: width/height (stops layout shift), decoding=async
  const tags = [...new Set(h.match(/<img\s[^>]*>/g) || [])];
  for (const tag of tags) {
    let t = tag;
    const src = (t.match(/\ssrc="(\/[^"]+)"/) || [])[1];
    if (src && (!/\swidth=/.test(t) || !/\sheight=/.test(t)) && !/\swidth=|\sheight=/.test(t)) {
      const d = await dimsOf(src);
      if (d) { t = t.replace('<img', `<img width="${d[0]}" height="${d[1]}"`); imageStats.dims++; }
    }
    if (!/\sdecoding=/.test(t)) { t = t.replace('<img', '<img decoding="async"'); imageStats.decoding++; }
    if (t !== tag) h = h.split(tag).join(t);
  }
  // 3) the first image that is not lazy (the likely LCP image) gets high priority
  const first = (h.match(/<img\s[^>]*>/g) || []).find((t) => !/loading="lazy"/.test(t) && /\ssrc="\/images\//.test(t) && !/fetchpriority/.test(t));
  if (first) { h = h.replace(first, first.replace('<img', '<img fetchpriority="high"')); imageStats.priority++; }
  return h;
}

const walk = (d, a = []) => { for (const f of fs.readdirSync(d)) { const p = path.join(d, f); fs.statSync(p).isDirectory() ? walk(p, a) : f.endsWith('.html') && a.push(p); } return a; };
let changed = 0, links = 0;
for (const f of walk(DIST)) {
  let h = fs.readFileSync(f, 'utf8');
  const before = h;
  // internal links: href="/path"
  h = h.replace(/(\shref=)"(\/[^"]*)"/g, (all, attr, u) => {
    if (skip(u)) return all;
    const n = policy(u);
    if (n !== u) links++;
    return `${attr}"${n}"`;
  });
  // absolute links to this very site
  h = h.replace(new RegExp(`(\\shref=)"(${domain.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})(/[^"]*)?"`, 'g'), (all, attr, d, rest) => `${attr}"${d}${policy(rest || '/') === '/' ? '/' : policy(rest)}"`);
  // redirect stubs generated by Astro (meta refresh + canonical)
  h = h.replace(/(http-equiv="refresh" content="0;\s*url=)([^"]+)"/, (all, a, u) => {
    const rel = u.startsWith(domain) ? u.slice(domain.length) || '/' : u;
    return rel.startsWith('/') ? `${a}${policy(rel)}"` : all;
  });
  h = await optimiseImages(h);
  if (h !== before) { fs.writeFileSync(f, h); changed++; }
}
// CSS files (background images)
const cssFiles = (function w(d, a = []) { for (const n of fs.readdirSync(d)) { const p = path.join(d, n); fs.statSync(p).isDirectory() ? w(p, a) : n.endsWith('.css') && a.push(p); } return a; })(DIST);
for (const cf of cssFiles) {
  let c = fs.readFileSync(cf, 'utf8'); const b = c;
  c = c.replace(/url\((['"]?)(\/images\/[^)'"]+\.(?:jpe?g|png))\1\)/gi, (all, q, u) => `url(${q}${toWebp(u)}${q})`);
  if (c !== b) fs.writeFileSync(cf, c);
}
console.log(`postbuild: images -> ${imageStats.webp} to WebP, ${imageStats.dims} given width/height, ${imageStats.decoding} decoding=async, ${imageStats.priority} priority hints`);
console.log(`postbuild: URL policy = ${slash ? 'trailing slash' : 'no trailing slash'}; ${links} internal links normalised in ${changed} pages`);

// ---------------- prune: do not ship images that nothing references ----------------
// Scans every text file in dist (html, css, js, json, xml, webmanifest). An image stays if its path appears anywhere.
// Skip with:  PRUNE_IMAGES=0 npm run build
(function pruneImages() {
  if (process.env.PRUNE_IMAGES === '0') return;
  const all = (function w(d, a = []) { for (const n of fs.readdirSync(d)) { const p = path.join(d, n); fs.statSync(p).isDirectory() ? w(p, a) : a.push(p); } return a; })(DIST);
  const text = all.filter((p) => /\.(html|css|js|mjs|json|xml|webmanifest|txt)$/i.test(p));
  let blob = '';
  for (const p of text) blob += fs.readFileSync(p, 'utf8') + '\n';
  let removed = 0, bytes = 0;
  for (const p of all) {
    const rel = path.relative(DIST, p).split(path.sep).join('/');
    if (!rel.startsWith('images/') || !/\.(jpe?g|png|webp|gif|avif|svg)$/i.test(rel)) continue;
    if (blob.includes('/' + rel) || blob.includes('/' + encodeURI(rel))) continue;
    bytes += fs.statSync(p).size; fs.unlinkSync(p); removed++;
  }
  console.log(`postbuild: pruned ${removed} unreferenced images (${(bytes / 1048576).toFixed(0)} MB) from dist/images`);
})();
